### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Deathmeister1** [BLAMM67/Armageddon#1]
Game crashed again during the first night which of course is a blood moon.  Still dieing alot while waiting for a blood moon to pass.

**Comment by Deathmeister1** [comment]
Sent over some more crash reports.  There are way too many creatures at night for anyone to survive.  I'm done for now.

**Comment by BLAMM67** [comment]
If you leave crash reports in dropbox, post the file names with the issue description.

**Comment by BLAMM67** [comment]
Fixed the ticking entity crash by [removing skeletons from special_ai and idle_fiddling](https://github.com/BLAMM67/Armageddon/commit/71df6e0e99a08d73d13a9855a0f28fee36298446).
