### ISSUE TITLE
Quest does not complete when fullfilled

### ISSUE THREAD

**Issue by Deathmeister1** [BLAMM67/Armageddon#2]
Quest is under technology.
RTFM does not complete when you make the book.  I have even clicked the submit button.

**Comment by Deathmeister1** [comment]
Treat me right quest fails as well.  Under technology again.

**Comment by BLAMM67** [comment]
Fixed the _Treat Me Right_ quest along with all the other crafting quests that need to be retrieval quests under the _Technology_ chapter.
_RTFM_ behaved properly for me. Must have just been a glitch.
