### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by Deathmeister1** [BLAMM67/Armageddon#3]
Loaded the new update and keeps crashing.  I get into the game sometimes but as soon as I start moving I crash.

**Comment by Deathmeister1** [comment]
Played that time for a while until a creeper came up and blew me up.  Then crashed again.  Food disappears so damn quick and zombie pigmen are aggressive as all get out.  
[crash-2017-05-20_14.31.08-server.txt](https://github.com/BLAMM67/Armageddon/files/1016406/crash-2017-05-20_14.31.08-server.txt)

**Comment by Deathmeister1** [comment]
[crash-2017-05-20_14.37.38-server.txt](https://github.com/BLAMM67/Armageddon/files/1016414/crash-2017-05-20_14.37.38-server.txt)

**Comment by Deathmeister1** [comment]
[crash-2017-05-21_10.17.50-server.txt](https://github.com/BLAMM67/Armageddon/files/1017070/crash-2017-05-21_10.17.50-server.txt)
[crash-2017-05-21_10.23.12-server.txt](https://github.com/BLAMM67/Armageddon/files/1017071/crash-2017-05-21_10.23.12-server.txt)

**Comment by BLAMM67** [comment]
The mod SpecialAI has been removed from the pack.
